LeagueManager/LeagueManager/Controllers/HomeController.cs
using System.Web.Mvc;

namespace LeagueManager.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }
        public ActionResult BaseBall()
        {
            ViewBag.Message = "Baseball landing page.";

            return View();
        }
        public ActionResult BasketBall()
        {
            ViewBag.Message = "Basketball landing page.";

            return View();
        }
        public ActionResult CheerLeading()
        {
            ViewBag.Message = "Cheerleading landing page.";

            return View();
        }
        public ActionResult FootBall()
        {
            ViewBag.Message = "Football landing page.";

            return View();
        }
        public ActionResult Soccer()
        {
            ViewBag.Message = "Soccer landing page.";

            return View();
        }
        public ActionResult SoftBall()
        {
            ViewBag.Message = "Softball landing page.";

            return View();
        }
        public ActionResult PlayerAdd()
        {
            return View();
        }
        public ActionResult AssignPlayers()
        {
            return View();
        }
    }
}

LeagueManager/LeagueManager/Controllers/YouthPlayersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeagueManager.Models;

namespace LeagueManager.Controllers
{
    public class YouthPlayersController : Controller
    {
        private PlayerDbContext db = new PlayerDbContext();

        // GET: YouthPlayers
        public ActionResult Index()
        {
            return View(db.Players.ToList());
        }

        // GET: YouthPlayers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YouthPlayer youthPlayer = db.Players.Find(id);
            if (youthPlayer == null)
            {
                return HttpNotFound();
            }
            return View(youthPlayer);
        }

        // GET: YouthPlayers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: YouthPlayers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlayerID,FirstName,LastName,ParentID,Soccer,Baseball,Basketball,Softball,Cheerleading,Football")] YouthPlayer youthPlayer)
        {
            if (ModelState.IsValid)
            {
                db.Players.Add(youthPlayer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(youthPlayer);
        }

        // GET: YouthPlayers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YouthPlayer youthPlayer = db.Players.Find(id);
            if (youthPlayer == null)
            {
                return HttpNotFound();
            }
            return View(youthPlayer);
        }

        // POST: YouthPlayers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlayerID,FirstName,LastName,ParentID,Soccer,Baseball,Basketball,Softball,Cheerleading,Football")] YouthPlayer youthPlayer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(youthPlayer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(youthPlayer);
        }

        // GET: YouthPlayers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YouthPlayer youthPlayer = db.Players.Find(id);
            if (youthPlayer == null)
            {
                return HttpNotFound();
            }
            return View(youthPlayer);
        }

        // POST: YouthPlayers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            YouthPlayer youthPlayer = db.Players.Find(id);
            db.Players.Remove(youthPlayer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeagueManager/LeagueManager/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<address>
    Local Location<br />
    Here, OK 55555<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <p>Development Team :</p>
    <strong>Jordan Anderson:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Derek Phillips:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Andrew Billy:</strong>   <a href="mailto:Support@example.com">Support@example.com</a>
</address>
<p>Use this area to provide additional information.</p>

LeagueManager/LeagueManager/Views/Home/AssignPlayers.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

LeagueManager/LeagueManager/Views/Home/BaseBall.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>@ViewBag.Message</p>

LeagueManager/LeagueManager/Views/Home/BasketBall.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>@ViewBag.Message</p>

LeagueManager/LeagueManager/Views/Home/CheerLeading.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>@ViewBag.Message</p>

LeagueManager/LeagueManager/Views/Home/Coach.cshtml
@using Microsoft.AspNet.Identity;
@{
    
    if (User.Identity.IsAuthenticated && User.IsInRole("Coach") || User.IsInRole("Admin")) { 
    Layout = "~/Views/Shared/_Layout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/Error.cshtml";
    }
}


<p>@ViewBag.Message</p>

    <h1>Restricted: Coaches only!</h1>



LeagueManager/LeagueManager/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<hgroup>
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>
</hgroup>
<div>
    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <i class="icon-envelope"></i><strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <i class="icon-envelope"></i><strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</div>

LeagueManager/LeagueManager/Views/Home/FootBall.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>@ViewBag.Message</p>

LeagueManager/LeagueManager/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>League Manager</h1>
    <p class="lead">This is the place to set up some league / tournament stuffs.</p>
    <p> TODO: Derive User Role at this point and show link accordingly:</p>
    <p >@Html.ActionLink("About Us", "About")</p>
    <p>@Html.ActionLink("Add Player", "Index","YouthPlayers")</p>
    <p>@Html.ActionLink("Assign Players", "Index", "YouthPlayers")</p>
    
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Some Content Here</h2>
        <p>
            Some things with images for prettiness.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>And then More !</h2>
        <p>The aweseomness never ends with are limitless content !</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Finally</h2>
        <p>I'm not sure what is goin to be used for filler here....</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

LeagueManager/LeagueManager/Views/Home/PlayerAdd.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

LeagueManager/LeagueManager/Views/Home/Soccer.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>@ViewBag.Message</p>

LeagueManager/LeagueManager/Views/Home/SoftBall.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p>@ViewBag.Message</p>